name: RPShops
version: 1.0.0
main: com.scottwoodward.rpshops.RPShops

commands:
  shop:
    description: Sets up a shop
    usage: /shop
    permission: rpshops.command.shop
    permission-message: You don't have permission to set up a shop. 